---
title: "Untitled"
author: "u7151703"
date: "2023-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```


```{r}
compute_cdf <- function(data) {

  # Pair up weights and values into a list of tuples
  pairs <- matrix(data, ncol = 2, byrow = TRUE)
  
  # Compute the cumulative sum of weights
  weights <- numeric(length = nrow(pairs))
  rates <- numeric(length = nrow(pairs))
  
  weights[1] <- pairs[1, 1]
  rates[1] <- pairs[1, 2]
  
  for (i in 2:nrow(pairs)) {
    weights[i] <- weights[i-1] + pairs[i, 1]
    rates[i] <- pairs[i, 2]
  }
  
  weights[length(weights)] <- round(weights[length(weights)])
  result <- data.frame(weights,rates)
  result <- rbind(data.frame(weights = 0, rates = min(result$rates)), result)
  
  return(result)
}

```


```{r}
l10t90_1 <- c(0.2476,0.03401,0.166,0.1642,0.112,0.4501,0.1241,0.8255,0.1341,1.281,0.1461,2.143,0.05735,3.995,0.01282,7.601)
l10t90_2 <- c(0.2529,0.03379,0.1675,0.1613,0.1119,0.4548,0.122,0.8216,0.1309,1.291,0.1434,2.153,0.05825,4.033,0.01322,7.617)
l5t90_1 <- c(0.2447,0.03478,0.1654,0.1657,0.1128,0.4513,0.1237,0.8197,0.1345,1.276,0.1468,2.115,0.059,3.932,0.01298,7.526)
l5t90_2 <- c(0.2551,0.03314,0.1677,0.1549,0.111,0.4474,0.122,0.819,0.1294,1.29,0.1441,2.165,0.05749,4.081,0.01326,7.732)
l2t90_1 <- c(0.2796,0.04126,0.1727,0.246,0.1407,0.6401,0.1681,1.124,0.1643,2.021,0.06118,3.853,0.01335,7.43)
l2t90_2 <- c(0.08979,0,0.3066,0.09546,0.1231,0.4005,0.2069,0.898,0.1909,1.905,0.06766,3.836, 0.01511,7.436)
```

```{r}
l10t90_1 <- compute_cdf(l10t90_1)
l10t90_2 <- compute_cdf(l10t90_2)
l5t90_1 <- compute_cdf(l5t90_1)
l5t90_2 <- compute_cdf(l5t90_2)
l2t90_1 <- compute_cdf(l2t90_1)
l2t90_2 <- compute_cdf(l2t90_2)
```


```{r}
ggplot(result, aes(x = weights, y = rates)) +
  geom_step(direction = "vh",linewidth = 0.7) +
  geom_step(data = l10t90_2, direction = "vh",linewidth = 0.7, color = 'red') +
  geom_step(data = l5t90_1, direction = "vh",linewidth = 0.7, color = 'blue') +
  geom_step(data = l5t90_2, direction = "vh",linewidth = 0.7, color = 'orange') +
  geom_step(data = l2t90_1, direction = "vh",linewidth = 0.7, color = 'yellow') +
  geom_step(data = l2t90_2, direction = "vh",linewidth = 0.7, color = 'green') +
  coord_cartesian(xlim = c(0, 1)) +
  labs(title = "Cumulative Plot", x = "Weights", y = "Rates") +
  theme_minimal()
```

```{r}
# Add an initial data point to 'result' dataframe
result <- rbind(data.frame(weights = 0, rates = min(result$rates)), result)

# Plot
ggplot(result, aes(x = weights, y = rates)) +
  geom_step(direction = "vh", linewidth = 1) +
  coord_cartesian(xlim = c(0, 1)) +
  labs(title = "Cumulative Plot", x = "Weights", y = "Rates") +
  theme_minimal()

```






