---
title: "Untitled"
author: "u7151703"
date: "2023-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```


```{r}
ggplot(optimiser,aes(x = as.factor(classes),y = abs(lnl)))+
  geom_jitter(width = 0.15)+
  scale_y_log10()
```

```{r}
ise_q4$model1 <- factor(ise_q4$model1, levels = c('l2t50_1_q4_1', 'l2t50_1_q4_2', 'l2t50_1_q4_3', 'l2t50_1_q4_4', 'l2t50_1_q4_5', 'l2t50_1_q4_6', 'l2t50_1_q4_7', 'l2t50_1_q4_8', 'l2t50_1_q4_9', 'l2t50_1_q4_10'))
ise_q4$model2 <- factor(ise_q4$model2, levels = c('l2t50_1_q4_10', 'l2t50_1_q4_9', 'l2t50_1_q4_8', 'l2t50_1_q4_7', 'l2t50_1_q4_6', 'l2t50_1_q4_5', 'l2t50_1_q4_4', 'l2t50_1_q4_3', 'l2t50_1_q4_2', 'l2t50_1_q4_1'))

ggplot(ise_q4, aes(x = model1, y = model2, fill = ise_r))+
  geom_tile(color = "white", size = 2) +
  geom_text(aes(label = round(ise_r,3), vjust = 0.8),size = 3) + 
  scale_fill_gradient(low = "white", high = "red") +
  labs(title = "Paired ISE of ten Q4 replicates") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(optimiser %>% filter(classes == 4), aes(x = rep, y = abs(lnl)))+
  geom_point()+
  theme_minimal()+
  scale_y_log10()+
  labs(title = "loglikelihood of ten Q4 replicates") +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
```

```{r}
ise_q5$model1 <- factor(ise_q5$model1, levels = c('l2t50_1_q5_1', 'l2t50_1_q5_2', 'l2t50_1_q5_3', 'l2t50_1_q5_4', 'l2t50_1_q5_5', 'l2t50_1_q5_6', 'l2t50_1_q5_7', 'l2t50_1_q5_8', 'l2t50_1_q5_9', 'l2t50_1_q5_10'))
ise_q5$model2 <- factor(ise_q5$model2, levels = c('l2t50_1_q5_10', 'l2t50_1_q5_9', 'l2t50_1_q5_8', 'l2t50_1_q5_7', 'l2t50_1_q5_6', 'l2t50_1_q5_5', 'l2t50_1_q5_4', 'l2t50_1_q5_3', 'l2t50_1_q5_2', 'l2t50_1_q5_1'))

ggplot(ise_q5, aes(x = model1, y = model2, fill = ise_r))+
  geom_tile(color = "white", size = 2) +
  geom_text(aes(label = round(ise_r,3), vjust = 0.8),size = 3) + 
  scale_fill_gradient(low = "white", high = "red") +
  labs(title = "Paired ISE of ten Q5 replicates") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(optimiser %>% filter(classes == 5), aes(x = rep, y = abs(lnl)))+
  geom_point()+
  theme_minimal()+
  scale_y_log10()+
  labs(title = "loglikelihood of ten Q5 replicates") +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
```

```{r}
ggplot(bfgs_em,aes(x = type,y = abs(lnl)))+
  geom_jitter(width = 0.15)+
  scale_y_log10()
```

```{r}
ggplot(bfgs_em,aes(x = type,y = time/3600))+
  geom_jitter(width = 0.15)+
  labs(y = 'CPU hour')
```

