---
title: "Untitled"
author: "u7151703"
date: "2023-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
library(sem)
library(ggfortify)
library(devtools)
#library(ggbiplot)
library(ggrepel)
library(scatterplot3d)
library(readxl)
options(scipen=999)
```

```{r}
result_q10 <- read_excel("C:/Users/u7151703/Desktop/research/RFmixture/data/mammal/q10_12.xlsx")
View(result_q10)
```

```{r}
result_q10$AC_l <- log(result_q10$AC,base = 10)
result_q10$AG_l <- log(result_q10$AG,base = 10)
result_q10$AT_l <- log(result_q10$AT,base = 10)
result_q10$CG_l <- log(result_q10$CG,base = 10)
result_q10$CT_l <- log(result_q10$CT,base = 10)
```

```{r}
q10_sub <- result_q10 %>% filter(data %in% c('l10t90_1', 'l5t90_1', 'l2t90_1', 'l1t90_1','l10t90_2', 'l5t90_2', 'l2t90_2', 'l1t90_2'))
#q10_sub <- result_q10
#q10_sub <- result_q10 %>% filter(data %in% c('l10t90_1','l10t90_2','l2t90_1','l2t90_2'))

pca1 <- prcomp(q10_sub[,c(14:18)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$data <- q10_sub$data
df1$weight <- q10_sub$weight
df1$class <- q10_sub$class

ggplot(data = df1 %>% filter(data %in% c('l10t90_1','l10t90_2','l2t90_1','l2t90_2')) ,aes(x = PC1,y = PC2,color = data))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()
```

```{r}
df1$data <- q10_sub$data
df1$weight <- q10_sub$weight
df1$class <- q10_sub$class

ggplot(data = df1 %>% filter(data %in% c('l2t90_1')) ,aes(x = PC1,y = PC2,color = data))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()
```


```{r}
df1$data <- q10_sub$data
df1$weight <- q10_sub$weight
df1$class <- q10_sub$class

ggplot(data = df1 %>% filter(data %in% c('l10t90_1','l2t90_1')) ,aes(x = PC1,y = PC2,color = data))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()
```

```{r}
ggplot(data = df1 ,aes(x = PC1,y = PC2,color = q10_sub$data))+
  geom_point(aes(size = q10_sub$weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  #geom_text(aes(label = q10_sub$class), vjust = 1.5, size = 3.5)+ 
  theme_bw() 
```


```{r}
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
zlab1 <- paste0("PC3(",round(summ1$importance[2,3]*100,2),"%)")

color = c(rep('red',10),rep('blue',10))
s3d <- scatterplot3d(df1[,1:3],color= color, pch = 16,angle=30,box=T,type="p",lty.hide=2,lty.grid = 2,xlab = xlab1, ylab = ylab1, zlab = zlab1)
text(s3d$xyz.convert(df1[, 1:3]),labels = result_q10$class, pos = 4, cex = 0.8, col = color)
legend("topright",c('l10t90_1','l10t90_2'),fill=c('red','blue'),box.col=NA)
```



```{r}
pca2 <- prcomp(result_q10[,c(10:13)],center = FALSE,scale. = FALSE)
```

```{r}
df2 <- pca2$x 
df2 <- as.data.frame(df2) 

summ2 <- summary(pca2)
xlab2 <- paste0("PC1(",round(summ2$importance[2,1]*100,2),"%)")
ylab2 <- paste0("PC2(",round(summ2$importance[2,2]*100,2),"%)")
```

```{r}
ggplot(data = df2,aes(x = PC1,y = PC2,color = result_q10$data))+
  #stat_ellipse(aes(fill = result_q10$data), type = "norm",geom = "polygon",alpha = 0.25,color = NA)+ 
  geom_point(aes(size = result_q10$weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  theme_bw()+
  geom_text(aes(label = result_q10$class), vjust = 1.5, size = 3.5) 
```




