---
title: "Untitled"
author: "u7151703"
date: "2023-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
```

```{r}
plot_data_inc2 <- mf_results_dec2 %>%
  pivot_longer(cols = -partition,
               names_to = "model",
               values_to = "order")
```

```{r}
plot_data_inc2$model <- factor(plot_data_inc2$model, 
                               levels = c('d1_100loci','d2_100loci',
                                          'd1_200loci','d2_200loci',
                                          'd1_500loci','d2_500loci',
                                          'd1_1000loci','d2_1000loci',
                                          'q1'))
ggplot(plot_data_inc2 %>% filter(order == 1),aes(x = model))+
  geom_bar(fill = 'red')+
  labs(x = 'training data', y = 'count')+
  theme_bw()
```

```{r}
plot_data_dec2 <- mf_results_dec_plant %>%
  pivot_longer(cols = -partition,
               names_to = "model",
               values_to = "order")
```

```{r}
ggplot(plot_data_dec2,aes(x = model))+
  geom_bar(aes(fill = as.character(order)))
```


```{r}
mix_q10_long <- mix_vs_q10 %>%
  pivot_longer(cols = c('lnl', 'bic', 'time'), names_to = "item") %>%
  arrange("item") %>%
  group_by(row_number()) %>%
  summarise_all(~first(.), .groups = 'drop')
```


```{r}
ggplot(mix_q10_long,aes(x= item, fill = value))+
  geom_bar()+
  labs(y= 'better')+
  theme_bw()
```

```{r}
mix_q10_time <- mix_vs_q10 %>% slice(101:n()) %>%
  pivot_longer(cols = c('time_q10', 'time_mix'), names_to = "method") %>%
  arrange("method") %>%
  group_by(row_number()) %>%
  summarise_all(~first(.), .groups = 'drop')

mix_q10_time$method[which(mix_q10_time$method == 'time_q10')] <- 'Q10(consencus)'
mix_q10_time$method[which(mix_q10_time$method == 'time_mix')] <- 'MixtureFinder'
```

```{r}
ggplot(mix_q10_time, aes(x= length, y = value/3600, color = item))+
  geom_point()+
  labs(y = 'time(h)')
```

```{r}
ggplot(mix_q10_time, aes(x= classes,y = value/3600,color= method))+
  geom_jitter(data = mix_q10_time %>% filter(method == 'Q10(consencus)'),aes(x = classes-0.2, y = value/3600),width =0.15)+
  geom_jitter(data = mix_q10_time %>% filter(method == 'MixtureFinder'),aes(x = classes+0.2, y = value/3600),width =0.15)+
  scale_x_continuous(breaks = c(2,3,4,5,6,7,8,9))+
  labs(y = 'time(h)')+
  theme_bw()
```


```{r}
ggplot(mix_vs_q10,aes(x =classes, y = length, color = time_mix))+
  geom_jitter()+
  scale_x_continuous(breaks = c(2,3,4,5,6,7,8,9))+
  scale_color_viridis_c(option = "magma")
```

```{r}
ggplot(mix_vs_q10,aes(x = as.character(classes)))+
  geom_bar()+
  labs(x = 'classes by MixtureFinder')+
  theme_bw()
```

```{r}
ggplot(mix_vs_q10,aes(x = length))+
  geom_density()+
  labs(x = 'sites')+
  theme_bw()
```

```{r}
weights_plot <- weights %>%
  pivot_longer(cols = -partition,
               names_to = "index",
               values_to = "weight")

weights_plot$index <- factor(weights_plot$index, levels = c('w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10'))

ggplot(weights_plot, aes(x = weight))+
  geom_density()+
  facet_wrap(~index)+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w1'), aes(xintercept = 0.0887), color = 'red')+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w2'), aes(xintercept = 0.0471), color = 'red')+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w3'), aes(xintercept = 0.0796), color = 'red')+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w4'), aes(xintercept = 0.0914), color = 'red')+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w5'), aes(xintercept = 0.1133), color = 'red')+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w6'), aes(xintercept = 0.0860), color = 'red')+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w7'), aes(xintercept = 0.1725), color = 'red')+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w8'), aes(xintercept = 0.0671), color = 'red')+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w9'), aes(xintercept = 0.1205), color = 'red')+
  geom_vline(data = weights_plot %>% filter(weights_plot$index == 'w10'), aes(xintercept = 0.1348), color = 'red')
```



